services:
  crafty-client:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: crafty_client
    restart: unless-stopped
    user: "node"
    read_only: true
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    tmpfs:
      - /tmp:uid=1000,gid=1000,mode=1777
      - /app/.next/cache:uid=1000,gid=1000,mode=700
    pids_limit: 200
    environment:
      NODE_ENV: production
      NEXT_TELEMETRY_DISABLED: "1"
    env_file:
      - .env
    networks:
      - frontend-internal

networks:
  frontend-internal:
    external: true
